const words = {
  before: '변경 전',
  after: '변경 후',
  beforeStatus: '변경 전 상태',
  afterStatus: '변경 후 상태',
  beforeRole: '변경 전 역할',
  afterRole: '변경 후 역할',
  createdRole: '발급 역할',
  mustChangePassword: '비밀번호 변경 필요',
  changeType: '변경 방식',
  reasonCode: '사유',
  failedCount: '로그인 실패 횟수',
  lockedUntil: '잠금 종료 시각',
  sessionId: '로그인 세션 ID',
  revokedReason: '세션 종료 사유',
  active: '활성 여부',
  published: '공개 여부',
  status: '상태',
  category: '분류',
  displayOrder: '표시 순서',
  question: '질문',
  answer: '답변',
  adminAnswer: '관리자 답변',
  assignedAdminId: '담당 관리자 ID',
  assignedAt: '담당 배정 시각',
  escalatedAt: '상담사 연결 요청 시각',
  closedAt: '종료 시각',
  resolvedAt: '해결 시각',
  reason: '사유',
  inquiryType: '문의 유형',
  priority: '우선순위',
  knowledgeDocumentId: '지식 문서 ID',
  version: '버전',
  processingStatus: '처리 상태',
  processingAttemptCount: '처리 시도 횟수',
  failureCode: '실패 사유',
  retryable: '재시도 가능',
  summaryJobId: '요약 작업 ID',
  traceId: '추적 ID',
  ACTIVE: '활성',
  INACTIVE: '미이용',
  WITHDRAWN: '탈퇴',
  SUSPENDED: '이용 정지',
  ADMIN: '관리자',
  SUPER_ADMIN: '최고 관리자',
  CUSTOMER: '고객',
  RIDER: '기사',
  SYSTEM: '시스템',
  SUCCESS: '성공',
  FAILURE: '실패',
  BLOCKED: '차단',
  COMPLETED: '완료',
  FAILED: '실패',
  PENDING: '대기',
  PROCESSING: '처리 중',
  REGISTERED: '등록됨',
  READY: '준비 완료',
  OPEN: '접수',
  IN_PROGRESS: '처리 중',
  RESOLVED: '해결',
  CLOSED: '종료',
  AI_ACTIVE: 'AI 상담 중',
  WAITING_ADMIN: '상담사 연결 대기',
  ADMIN_ACTIVE: '상담사 상담 중',
  SELF_CHANGE: '본인 변경',
  SUPER_ADMIN_RESET: '최고 관리자 초기화',
  SUPER_ADMIN_MANUAL_UNLOCK: '최고 관리자 잠금 해제',
  LOCK_EXPIRED: '잠금 시간 만료',
  INVALID_CREDENTIALS: '로그인 정보 불일치',
  LOGIN_FAILURE_LIMIT: '로그인 실패 횟수 초과',
  REFRESH_TOKEN_REUSE: '갱신 토큰 재사용 감지',
  DELIVERY_ASSIGNMENT_ISSUE: '배송 배정 문제',
  DELIVERY_GROUP: '배송 그룹',
  RIDER_LEAVE_REQUEST: '기사 휴무 신청',
  RIDER_SCHEDULE_EXCEPTION: '기사 일정 변경',
  ASSIGNMENT_ISSUE_REASSIGNED: '배정 문제 재배정',
  ASSIGNMENT_ISSUE_REJECTED: '배정 문제 반려',
  DELIVERY_GROUP_CONFIRMED: '배송 그룹 확정',
  EMERGENCY_RIDER_REPLACED: '긴급 기사 교체',
  MANUAL_ASSIGNMENT_CREATED: '수동 배정',
  RIDER_LEAVE_APPROVED: '기사 휴무 승인',
  RIDER_LEAVE_REJECTED: '기사 휴무 반려',
  RIDER_LEAVE_REQUESTED: '기사 휴무 신청',
  RIDER_SCHEDULE_EXCEPTION_CREATED: '기사 일정 변경 등록',
  RIDER_SCHEDULE_EXCEPTION_UPDATED: '기사 일정 변경 수정',
  RIDER_SCHEDULE_EXCEPTION_DELETED: '기사 일정 변경 삭제',
  DELIVERY_ACTIVE_CHANGED: '배송 참여 상태 변경',
  ASSIGNED: '배정됨',
  ISSUE_REPORTED: '문제 신고',
  REASSIGNED: '재배정',
  REJECTED: '반려',
  resolution: '처리 결과',
  assignmentId: '배정 ID',
  assignmentStatus: '배정 상태',
  riderId: '기사 ID',
  previousAssignmentId: '이전 배정 ID',
  previousAssignmentStatus: '이전 배정 상태',
  newAssignmentId: '새 배정 ID',
  newAssignmentStatus: '새 배정 상태',
  newRiderId: '새 기사 ID',
}

export const auditWord = (value) => words[value] || value

export function auditDetails(detail, prefix = '') {
  if (detail == null) return []
  if (typeof detail !== 'object') return [{ label: prefix || '상세 내용', value: display(detail) }]
  return Object.entries(detail).flatMap(([key, value]) => {
    const name = [prefix, words[key] || '추가 항목'].filter(Boolean).join(' · ')
    return value !== null && typeof value === 'object'
      ? auditDetails(value, name)
      : [{ label: name, value: display(value) }]
  })
}
function display(value) {
  if (value == null || value === '') return '없음'
  if (typeof value === 'boolean') return value ? '예' : '아니요'
  if (typeof value === 'string')
    return words[value] || (/^[A-Z][A-Z_]+$/.test(value) ? '기타 상태 (원본 기록 참고)' : value)
  return String(value)
}
